config/routes.rb
JANBnB::Application.routes.draw do

  devise_for :users, :controllers => { :registrations => :registrations }
  resources :users
  resources :properties do
    resources :photos
  end


  root 'users#index'



end

app/models/photo.rb
class Photo < ActiveRecord::Base
  has_attached_file :pic, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :pic, :content_type => /\Aimage\/.*\Z/
  belongs_to :property
end

app/models/property.rb
class Property < ActiveRecord::Base

  belongs_to :user
  has_many :photos

  validates :name, :presence => true
  validates :description, :presence => true
  validates :location, :presence => true
  validates :user_id, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  after_create :send_welcome_message

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :properties
  validates :name, :presence => true
  validates :bio, :presence => true

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/


  def send_welcome_message
    UserMailer.signup_confirmation(self).deliver
  end

  def greeting
    if Time.now.hour >= 17
      return "Good Evening"
    elsif Time.now.hour > 12
      return "Good Afternoon"
    else
      return "Good Morning"
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?




  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << [:name, :bio, :avatar, :owner]
    devise_parameter_sanitizer.for(:account_update) << [:name, :bio, :avatar, :owner]
  end

  def after_sign_in_path_for(user)
    user_path(@user)
  end


end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  def new
    @photo = Photo.new
    @property = Property.find(params[:property_id])
  end

  def create
    @property = Property.find(params[:property_id])
    @photo = @property.photos.new(photo_params)
    if @photo.save
      respond_to do |format|
        format.html { redirect_to property_path(@property) }
        format.js
      end
    else
      render 'property_path(@property)'
    end
  end

  def destroy
    @photo = Photo.destroy(params[:id])
    respond_to do |format|
      format.html { redirect_to user_url(current_user) }
      format.js
    end
  end

private

  def photo_params
    params.require(:photo).permit(:caption, :property_id, :pic)
  end

end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController

  def index
  end

  def new
    @property = Property.new
  end

  def create
    @property = Property.new(property_params)
    if @property.save
      respond_to do |format|
        format.html { redirect_to user_path(current_user) }
        format.js
      end
    else
      render 'user_path(current_user)'
    end
  end

  def show
    @property = Property.find(params[:id])
    @user = @property.user
  end

  def edit
    @property = Property.find(params[:id])
  end

  def update
    @property = Property.find(params[:id])
    @property.update(property_params)
    respond_to do |format|
      format.html { redirect_to property_url(@property) }
      format.js
    end
  end

  def destroy
    @property = Property.destroy(params[:id])
    respond_to do |format|
      format.html { redirect_to user_url(current_user) }
      format.js
    end
  end

private

  def property_params
    params.require(:property).permit(:name, :location, :description, :user_id)
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  protected

    def after_update_path_for(user)
      user_path(@user)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

def index

end

def new
  @user = User.new
end

def create
  @user = User.new(user_params)
  if @user.save
    flash[:notice] = "Profile created"
    redirect_to user_path(@user)
  else
    render 'new'
  end
end

def show
  @user = User.find(params[:id])
  @properties = @user.properties
end

def update
  @user = User.find(params[:id])
end


private
  def user_params
    params.require(:user).permit(:name, :bio, :avatar, :owner, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>

<h3>Please fix the following:</h3>
<ul>
  <% object.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
</ul>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JANBnB</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <div id="user_nav">
    <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to 'Edit profile', edit_user_registration_path %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path %> |
      <%= link_to "Log in", new_user_session_path %>
    <% end %>
  </div>
  <title><%= yield(:title) %></title>

  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, id: "flash_#{name}" %>
  <% end %>

  <%= yield %>

</div>

</body>
</html>

app/views/photos/_form.html.erb
<%= render "layouts/errors", :object => @photo %>

<%= form_for [@property, @photo], remote: true, authenticity_token: true, :html => { :multipart => true } do |f| %>

  <div class="form-group">
    <%= f.label :caption %>
    <%= f.text_field :caption %>
  </div>
  <div class="form-group">
    <%= f.label :pic, "Select a photo" %>
    <%= f.file_field :pic %>
  </div>

  <%= f.submit(:class => 'btn btn-primary') %>

<% end %>

app/views/photos/_photo.html.erb
<li id="photo_<%= photo.id %>">

  <%= image_tag photo.pic.url(:thumb) %> <br>
  <%= photo.caption %> <br>
  <%= link_to "(delete)", property_photo_path(@property, photo), method: :delete, data: {confirm: "Are you sure?"}, remote: true %>

</li>

app/views/photos/create.js.erb
$('#new_photo').remove();
$('#new_photo_link').show();
$('#all_photos').append('<%= j render(@photo) %>');

app/views/photos/destroy.js.erb
$('#photo_<%= @photo.id %>').remove();

app/views/photos/new.js.erb
$('#new_photo_link').hide().after('<%= j render("form") %>');

app/views/properties/_form.html.erb
<%= render "layouts/errors", :object => (@property) %>
<%= form_for @property, remote: true do |f| %>
  <h3>Property Details:</h3>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>
  <div class="form-group">
    <%= f.label :location %>
    <%= f.text_field :location %>
  </div>
  <div class="form-group">
    <%= f.hidden_field :user_id, :value => current_user.id %>
  </div>
  <%= f.submit(:class => 'btn btn-primary') %>
<% end %>

app/views/properties/_property.html.erb
<li id="property_<%= property.id %>">

  <div class="strong"><%= link_to "#{property.name}", property_path(property) %></div>
  <%= link_to "(delete)", property, method: :delete, data: {confirm: "Are you sure?"}, remote: true %>
  <br>
  <br>

</li>

app/views/properties/create.js.erb
$('#new_property').remove();
$('#new_link').show();
$('#userprops ul').append('<%= j render(@property) %>');

app/views/properties/destroy.js.erb
$('#property_<%= @property.id %>').remove();

app/views/properties/edit.js.erb
$('#edit_property_link').hide().after('<%= j render("form") %>');

app/views/properties/new.html.erb
<% content_for(:title, "Add Listing | JANBnB") %>

<h1>Add a Property Listing: </h1>
<br />
<br />
<%= render 'form' %>

<br>
<br>
<br>
<br>
<%= link_to "Profile", user_path(current_user), class: 'btn btn-warning' %>

app/views/properties/new.js.erb
$('#new_link').hide().after('<%= j render("form") %>');

app/views/properties/show.html.erb
<% content_for(:title, "#Listing: {@property.name} | JANBnB") %>
<div class="house">
  <h1 id="prop_name"><%= @property.name %></h1>

  <div>

    <% if @property.photos != nil %>
      <ul id="all_photos" class="unstyled">
        <%= render @property.photos %>
      </ul>
    <% end %>

  </div>

  <h3 id="prop_location">Location:</h3>
  <p class="indent"><%= @property.location %></p>
  <br>
  <br>
  <h3 id="prop_description">Description:</h3>
  <p class="indent"><%= @property.description %></p>
  <br>
  <br>
  <% if @property.user_id == current_user.id %>
    <%= link_to 'Add Picture', new_property_photo_path(@property), class: 'btn btn-primary', remote: true, id: "new_photo_link" %>
    <%=  link_to 'Edit Property Details', edit_property_path(@property), class: 'btn btn-primary', remote: true, id: "edit_property_link" %>
  <% end %>
</div>

<div class="host">
<h3>Host:</h3>
<p><%= image_tag @user.avatar.url(:thumb) %></p>
<p class="indent">Meet <%= @user.name %></p>
<p class="indent"><%= @user.bio %></p>
</div>

<br />
<br />

app/views/properties/update.js.erb
$('#edit_property_<%= @property.id %>').remove();
$('#edit_property_link').show();
$('#prop_name').html('<%= @property.name %>')
$('#prop_location').html('<%= @property.location %>')
$('#prop_description').html('<%= @property.description %>')

app/views/users/_form.html.erb
<%= render("layouts/errors", :object => @user) %>
<% form_for(@user) do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%=  f.text_field :name %>
  </div>
  <div class="form-group">
    <%= f.label :bio %>
    <%= f.text_field %>
  </div>
  <div class="form-group">
    <%= f.label :avatar, "photo" %>
    <%= f.file_field :avatar %>
  </div>
  <div class="owner">
    <%= f.label :owner, "Are you a property owner?" %>
    <%= f.radio_button :owner, "true", :checked => true %>
    <%= f.radio_button :owner, "false", :checked => false %>
  </div>
  <%= f.submit(:class => 'btn btn-primary') %>
<% end %>

app/views/users/index.html.erb
<% content_for(:title, "Sign Up or In | JANBnB") %>

<h1>Welcome</h1>
<div class="indent">
<h1>JanBNB</h1>
</div>

app/views/users/new.html.erb
<% content_for(:title, "Sign Up | JANBnB") %>

<h2>Welcome to JanBnB</h2>

app/views/users/show.html.erb
<% content_for(:title, "#{@user.name} | JANBnB") %>


<h1><%= current_user.greeting %>, <%= current_user.name %></h1>
<br />
<br />
<div class="bio">
  <h3>Your Bio</h3>
  <%= current_user.bio %>
</div>

<div class="avatar">
  <%= image_tag current_user.avatar.url(:thumb) %>
</div>
<br />
<br />
<br />
<br />
<br />
<div id="userprops">
  <ul >
    <%= render @properties %>
  </ul>
</div>

<div class="well property">
<%= link_to 'Add Property', new_property_path, class: 'btn btn-warning', remote: true, id: "new_link"  %>
</div>